spring.application.name=cleanwheels-manager
spring.datasource.url=jdbc:h2:mem:lavajatodb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect